<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Roaster | APOLLO</title>
  <link rel="stylesheet" href="/roaster/style.css?v=10.7.5"> 
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
</head>
<body>
  <header>
      <div class="insideHeader">
    	<div class="menu"> 
    		<a href="/home-new/"><img src="../fonts/logo.png" /></a>
    	</div>
    	<div class="menuRight">
    	<h4 class="authorsNames" style="display:none;"></h4>
	    <ul>
	        <li>
	            <a href="/work/">roster</a>
	        </li>
	        <li>
	            <a href="/contact/">contact</a>
	       </li>
	    </ul>
	</div> 
      </div> 
    </header>
  <div class="video-container">
    <div class="seperator">Jamil Shaukat</div>     
    
       <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/7w52-uK-KwO2eWCfwCEDjQ/false/auto/auto/ffffff/000000" data-title="Ruroc - Berserker" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Ruroc - Berserker" data-videoSubName="Anytime, Anywhere" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>KC Locke</a><br> <b>Executive Producer:</b> <a href='#'>KC Locke</a><br> <b>Producer:</b> <a href='#'>Lewis Nicholson</a><br> <b>Production Company:</b> <a href='#'>Swords & Eagles</a><video poster="videos/images/nv1.jpg" src="videos/short/nv1.mp4" muted autoplay loop></video><label>Ruroc - Berserker</label></div>
    
    <div class="video EDITOR jamil-shaukat" data-longVideo="https://apollo.gosimian.com/share/v/-q-nJk-MzyUmkAPIljAdAw/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Look" data-videoSubName="Fantastic" data-credit="no" data-credits=""><video poster="videos/images/nv2.jpg" src="videos/short/nv2.mp4" muted autoplay loop></video><label>Look Fantastic</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/Z_N4ZKx8zseoxuWWEO5J9A/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Drama Call" data-videoSubName="Heaviest in the Game" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@Rawtape</a><br> <b>Production Company:</b> <a href='#'>@Antfarmfilmservices</a><br> <b>DP: <a href='#'>@jameskilleendop</a><br> <b>Post Production:</b> <a href='#'>@absolute_post</a><br> <b>Colour Producer:</b> <a href='#'>@ollieireland</a><br> <b>Colourist:</b> <a href='#'>@turners_colour</a><br> <b>Sound Producer:</b> <a href='#'>@Maddylebel</a><br> <b>Sound Design:</b> <a href='#'>@Argington</a>"><video poster="videos/images/nv3.jpg" src="videos/short/nv3.mp4" muted autoplay loop></video><label>Drama Call - Heaviest in the Game</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/OoYHiz7arVaXh-_3xR3o7g/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="CP Company" data-videoSubName="Manchester City" data-credit="yes" data-credits=""><video poster="videos/images/nv4.jpg" src="videos/short/nv4.mp4" muted autoplay loop></video><label>CP Company x Manchester City</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/4QqEVVuhldXN_i8Bnr1ZYw/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Boohoo Man" data-videoSubName="World Cup" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> KC Locke<br> <b>Producer:</b> Lewis Nicholson<br> <b>Production Company:</b> Swords & Eagles<br> <b>Exec Producer/ Directors Rep:</b> Marisa Garner<br> <b>DOP:</b> Rowan Biddiscombe<br> <b>Production Manager & Art Director:</b> Jenny O'Sullivan<br> <b>Editor:</b> Jamil Shaukat"><video poster="videos/images/nv5.jpg" src="videos/short/nv5.mp4" muted autoplay loop></video><label>Boohoo Man - World Cup</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/rfxS53q1G8VO6asIkOW-mg/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Meekz" data-videoSubName="Mini Me's" data-credit="no" data-credits=""><video poster="videos/images/nv6.jpg" src="videos/short/nv6.mp4" muted autoplay loop></video><label>Meekz - Mini Me's </label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/7FWkr5CFwzqaqdHiwrvlww/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Ed Sheeran" data-videoSubName="Take Me Back To London feat. Stormzy, Jaykae & Aitch" data-credit="no" data-credits=""><video poster="videos/images/nv7.jpg" src="videos/short/nv7.mp4" muted autoplay loop></video><label>Ed Sheeran - Take Me Back To London feat. Stormzy, Jaykae & Aitch</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/qhF_Zr-_wpZEXebRRPM4YA/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Aitch" data-videoSubName="Learning Curve"  data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> KC LOCKE<br> <b>Production Company:</b> Swords & Eagles<br> <b>Exec Producer/Directors:</b> Rep Marisa Garner<br> <b>DOP:</b> Pieter Synman<br> <b>Production Designer:</b> Jenny O' Sullivan<br> <b>Editor:</b> Jamil Shaukat<br> <b>Production Manager:</b> Ella Taylor-Palfrey"><video poster="videos/images/nv8.jpg" src="videos/short/nv8.mp4" muted autoplay loop></video><label>Aitch - Learning Curve</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/qhF_Zr-_wpZEXebRRPM4YA/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Aitch" data-videoSubName="Learning Curve"  data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> KC LOCKE<br> <b>Production Company:</b> Swords & Eagles<br> <b>Exec Producer/Directors:</b> Rep Marisa Garner<br> <b>DOP:</b> Pieter Synman<br> <b>Production Designer:</b> Jenny O’ Sullivan<br> <b>Editor:</b> Jamil Shaukat<br> <b>Production Manager:</b> Ella Taylor-Palfrey"><video poster="videos/images/nv8.jpg" src="videos/short/nv8.mp4" muted autoplay loop></video><label>Aitch - Learning Curve</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/L3HZIYNTMRPdQazo9r5jIQ/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="M Huncho & Headie One" data-videoSubName="Warzone" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> KC Locke<br> <b>Producer:</b> Lewis Nicholson<br> <b>Production Company:</b> Swords & Eagles ⚔️🦅<br> <b>Exec Producer:</b> Marisa Garner<br> <b>DOP:</b> Matthew Emvin Taylor<br> <b>Art Director:</b> Jenny O’Sullivan<br> <b>Editor:</b> Jamil Shaukat<br> <b>Production Manager:</b> Ella Taylor-Palfrey"><video poster="videos/images/nv9.jpg" src="videos/short/nv9.mp4" muted autoplay loop></video><label>M Huncho & Headie One - Warzone</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/e_xK1H4Fp-Y8rhQhkSCckA/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="David Guetta" data-videoSubName="BEBE" data-credit="no" data-credits=""><video poster="videos/images/nv10.jpg" src="videos/short/nv10.mp4" muted autoplay loop></video><label>David Guetta x BEBE</label></div>
    <div class="seperator">Liam Tangum</div>    
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/l4iJTcmvUc9kqSQ3mcktIA/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Oakely" data-videoSubName="Kylian Mbappe" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Creative and production:</b> <a href='#'>@steptstudios</a><br> <b>Producer:</b> <a href='#'>@alexa_hinson</a><br> <b>Head of creative:</b> <a href='#'>@rachcity</a><br> <b>Production manager:</b> <a href='#'>@ioladgsn</a><br> <b>Director:</b> <a href='#'>@joaquimbayle</a><br> <b>Assistant Director:</b> <a href='#'>@basile_boudoux</a><br> <b>DP:</b> <a href='#'>@marquesangelo</a>"><video poster="videos/images/nv11.jpg" src="videos/short/nv11.mp4" muted autoplay loop></video><label>Oakely - Kylian Mbappe</label></div>
    <div class="video liam-tangum" data-longVideo="https://apollo.gosimian.com/share/v/dV859sXWTPiERH5CF6iyTQ/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="YMI Jeans" data-videoSubName="RFM" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> SOFIA CRISTINA ALVAREZ<br> <b>Producer:</b> MARLYN RODRIGUEZ<br> <b>Creative Director:</b> DALIA GISELE SAFFAR<br> <b>Editor:</b> LIAM TANGUM<br> <b>Colorist:</b> DYLAN HAGEMAN<br> <b>Sound Designer:</b> GLENN MORISSE"><video poster="videos/images/nv12.jpg" src="videos/short/nv12.mp4" muted autoplay loop></video><label>RFM Jeans</label></div>
    <div class="video brooks" data-longVideo="https://apollo.gosimian.com/share/v/2RyALL3vM1bbYlXn6hEOjQ/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Brooks" data-videoSubName="Sounds of Trail Running" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Production:</b> <a href='#'>@steptstudios</a><br> <b>Post Production:</b> <a href='#'>@lockteditorial</a><br> <b>Director:</b> <a href='#'>Liam Tangum</a><br> <b>DP:</b> <a href='#'>@nash.howe</a><br> <b>Head of Post:</b> <a href='#'>@mr.deliverables</a>"><video poster="videos/images/nv13.jpg" src="videos/short/nv13.mp4" muted autoplay loop></video><label>Brooks - Sounds of Trail Running</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/0oRqHg7RMp9cRtecFGac4g/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Bevel" data-videoSubName="Kyle Pitts" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director / DP:</b> <a href='#'>@franklinspov</a> <h3>Produced by The Kitchen Table</h3> <b>Post Production Company:</b> <a href='#'>@apolloposthouse</a><br> <b>Head of Post:</b> <a href='#'>@ap.mov</a><br> <b>Post Supervisor:</b> <a href='#'>@nasserboulaich</a><br> <b>Editor:</b> <a href='#'>@ltangum</a><br> <b>Colorist:</b> <a href='#'>@brianchrls</a>"><video poster="videos/images/nv14.jpg" src="videos/short/nv14.mp4" muted autoplay loop></video><label>Bevel - Kyle Pitts</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/QnNDO5jJPiweNaYkDbVNkQ/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Nowness" data-videoSubName="Short Film" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> Leo Pfeifer<br> <b>Prouction:</b> Alto Visuals<br> <b>Editor:</b> Liam Tangum<br> <b>Sound Design:</b> Chris Fleming<br> <b>Production Director:</b> Ariana Massery"><video poster="videos/images/nv15.jpg" src="videos/short/nv15.mp4" muted autoplay loop></video><label>Nowness - Short Film</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/CmHy4CgsSoqo5K58skbxDw/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="A Slice of Paradise" data-videoSubName="Short Film" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> Liam Tangum<br> <b>Executive Producers:</b> No Laying Up<br> <b>Cinematographer:</b> Jake Coury<br> <b>Producer:</b> Michael Nicholas<br> <b>Editors:</b> Liam Tangum & Lindsay Wilkins"><video poster="videos/images/nv16.jpg" src="videos/short/nv16.mp4" muted autoplay loop></video><label>A Slice of Paradise - Short Film</label></div>
    <div class="seperator">Griffin Olis</div> 
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/1z2wxMuQOojv0_l3j_3BUA/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Adidas" data-videoSubName="Speed Juice" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@dannymcnabb_</a><br> <b>Production Company:</b> <a href='#'>@resinprojects</a><br> <b>Motion Producer:</b> <a href='#'>@anno & @sydnyfuruichi</a><br> <b>First AD:</b> <a href='#'>@justbearit</a><br> <b>DP:</b> <a href='#'>@cory.burmester</a>"><video poster="videos/images/nv17.jpg" src="videos/short/nv17.mp4" muted autoplay loop></video><label>Adidas - Speed Juice</label></div> 
    <div class="video griffin-olis" data-longVideo="https://apollo.gosimian.com/share/v/hpcySoCWdlWWHzaW6P5WWA/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Fear of God" data-videoSubName="" data-credit="no" data-credits=""><video poster="videos/images/nv18.jpg" src="videos/short/nv18.mp4" muted autoplay loop></video><label>Fear of God </label></div>
    <div class="video kai-cenat" data-longVideo="https://apollo.gosimian.com/share/v/n0LFcwPS9X72xQRkpvugzw/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Kai Cenat" data-videoSubName="Going Professional" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Production Company:</b> <a href='#'>@blackscreenproductionsinc</a><br> <b>Director:</b> <a href='#'>@directorprime @lach531</a><br> <b>Executive Producers:</b> <a href='#'>@moniquescarrillo @directorprime</a><br> <b>Producer:</b> <a href='#'>@henryjwolf</a><br> <b>DP:</b> <a href='#'>@jon.charles</a>"><video poster="videos/images/nv19.jpg" src="videos/short/nv19.mp4" muted autoplay loop></video><label>Kai Cenat - Going Professional</label></div>
    <div class="video under-armour" data-longVideo="https://apollo.gosimian.com/share/v/eHWf8zsSuiwys697NlDV3A/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Under Armour" data-videoSubName="Men Unstoppable Collection" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@waboosh</a><br> <b>Executive Producers/Parallel Studios:</b> <a href='#'>@tonypillow @Simonchasalow</a><br> <b>Executive Producer/GoBam:</b> <a href='#'>Chris Charlton</a><br> <b>Lead Producer:</b> <a href='#'>@msjonesa</a><br> <b>Head of Post:</b> <a href='#'>@ap.mov</a><br> <b>DP:</b> <a href='#'>@cory.burmester</a>"><video poster="videos/images/nv20.jpg" src="videos/short/nv20.mp4" muted autoplay loop></video><label>Under Armour - Men's Unstoppable Collection </label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/k84zVfx6eUANCz9rc-axFQ/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Kai Cenat x iShowSpeed Streamshow" data-videoSubName="Kai Cenat" data-credit="no" data-credits=""><video poster="videos/images/nv21.jpg" src="videos/short/nv21.mp4" muted autoplay loop></video><label>Kai Cenat x iShowSpeed</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/5jtkQ-J-7bk3e1C4p_1hwQ/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="MLS & Apple TV" data-videoSubName="Beyond the Pitch - Episode 2" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Editor:</b> <a href='#'>@blaizefobbe</a><br> <b>Post Production Supervisor:</b> <a href='#'>@ap.mov</a><br> <b>Director:</b> <a href='#'>@mediadon</a><br> <b>Executive Producers:</b> <a href='#'>@ap.mov @justnateloucks</a><br> <b>Producers:</b> <a href='#'>@waboosh @masendaforever</a><br> <b>Production Manager:</b> <a href='#'>@connectwithdiego</a><br> <b>Media Company:</b> <a href='#'>@boardroom</a><br> <b>Production Co:</b> <a href='#'>@parallelstudios</a>"><video poster="videos/images/MLS_Episode_2.png" src="videos/short/MLS_Episode_2.mp4" muted autoplay loop></video><label>MLS & Apple TV - Beyond the Pitch - Episode 2</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/_m2_Z8QG2n7FMj9u6qLWZA/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="MLS & Apple TV" data-videoSubName="Beyond the Pitch - Episode 4" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Editor:</b> <a href=''>@blaizefobbe</a><br> <b>Post Production Supervisor:</b> <a href=''>@ap.mov</a><br> <b>Director:</b> <a href=''>@mediadon</a><br> <b>Executive Producers:</b> <a href=''>@ap.mov @justnateloucks</a><br> <b>Producers:</b> <a href=''>@waboosh @masendaforever</a><br> <b>Production Manager:</b> <a href=''>@connectwithdiego</a><br> <b>Media Company:</b> <a href=''>@boardroom</a><br> <b>Production Co:</b> <a href=''>@parallelstudios</a>"><video poster="videos/images/MLS_Episode_4.png" src="videos/short/MLS_Episode_4.mp4" muted autoplay loop></video><label>MLS & Apple TV - Beyond the Pitch- Episode 4</label></div>
    <div class="seperator">Devon Solwold</div> 
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/hKEJPCvrM6F1f_D8m775gw/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Bodega" data-videoSubName="New Balance" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@nottonightmike</a><br> <b>Producer:</b> <a href='#'>@lizkraushaar</a><br> <b>DOP:</b> <a href='#'>@kajdickson</a><br> <b>Editor + Sound Designer:</b> <a href='#'>@devon.solwold</a><br> <b>Music:</b> <a href='#'>@mr.audreyhorne</a><br> <b>Executive Producer:</b> <a href='#'>@alexmajher</a>"><video poster="videos/images/eds1.png" src="videos/short/eds1.mp4" muted autoplay loop></video><label>Bodega x New Balance</label></div> 
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/tP8hab455lYbINecxlO4UA/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Bodega x G Shock" data-videoSubName="Anytime, Anywhere" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>Michael B Janey @nottonightmike</a><br> <b>Cinematographer:</b> <a href='#'>Kai Dickson @kaj_dickson</a><br> <b>Post Producer:</b> <a href='#'>Elizabeth Kraushaar @liz_kraushaar</a><br> <b>Editor + Sound Designer:</b> <a href='#'>Devon Solwold @devon.solwold</a><br> <b>Colorist:</b> Kai Dickson<br> <b>Agency:</b> <a href='#'>@drinkadmilk</a>"><video poster="videos/short/bodega-g-shock-anytime-anywhere.png" src="videos/short/bodega-g-shock-anytime-anywhere.mp4" muted autoplay loop></video><label>Bodega x G Shock - Anytime, Anywhere</label></div>
    <div class="video devon-solwold" data-longVideo="https://apollo.gosimian.com/share/v/Kj037VYYf3TRWAyj2X9grw/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="OKEM" data-videoSubName="Short Film" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> Joshua Okwuosa<br> <b>Cinematography:</b> Kai Dickson<br> <b>Music:</b> Jake Hull<br> <b>Editing:</b> Devon Solwold<br> <b>Producer:</b> Liz Kraushaar"><video poster="videos/images/eds3.png" src="videos/short/eds3.mp4" muted autoplay loop></video><label>OKEM - Short Film</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/MdBuv2VRG7aBrCpyi2NlzQ/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Eem Triplin" data-videoSubName="What Da Opp Said" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@waboosh</a><br> <b>Executive Producers:</b> <a href='#'>@tonypillow @simonchasalow @_lucasprevost</a><br> <b>Producer:</b> <a href='#'>@noursayeh</a><br> <b>Production Manager:</b> <a href='#'>@natallejastrow</a><br> <b>Head of Production Support:</b> <a href='#'>@tj.gormley</a><br> <b>Production Company:</b> <a href='#'>@parallelstudios</a>"><video poster="videos/images/eds4.png" src="videos/short/eds4.mp4" muted autoplay loop></video><label>Eem Triplin - What Da Opp Said</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/roJJm677DwOEfWAHUBszjw/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="$NOT feat. Zilla Kami" data-videoSubName="0 PERCENT" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@jmp</a><br> <b>Executive Producer:</b> <a href='#'>@joeyszela</a><br> <b>Producer:</b> <a href='#'>@tru.drew</a><br> <b>DP:</b> <a href='#'>@joelwolt</a><br> <b>Production Company:</b> <a href='#'>@paperwork</a>"><video poster="videos/short/NOT-Ft-Zilla-Kami-0-PERCENT.png" src="videos/short/NOT-Ft-Zilla-Kami-0-PERCENT.mp4" muted autoplay loop></video><label>$NOT feat. Zilla Kami - 0 PERCENT</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/OajoX7MS0eM11zx97Mov9Q/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Run that Shit!" data-videoSubName="Short Film" data-credit="yes" data-credits="<h3>Apollo</h3> <b>EXECUTIVE PRODUCERS:</b> Tristan Kim, Harrison Kracht<br> <b>DIRECTOR:</b> Tristan Kim<br> <b>WRITTEN BY:</b> Tristan Kim, Will Allyn Robinson<br> <b>DIRECTOR OF PHOTOGRAPHY:</b> Harrison Kracht"><video poster="videos/images/eds6.png" src="videos/short/eds6.mp4" muted autoplay loop></video><label>Run that Shit! Short Film</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/pnUrDJ8rUy0z_wgrQsLUPg/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="PURPLE DENIM" data-videoSubName="Daytrippin" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Edit, Sound, VFX:</b> <a href='#'>@devon.solwold</a><br> <b>Studio:</b> <a href='#'>@drinkadmilk</a><br> <b>Producer:</b> <a href='#'>@alexmajher</a>"><video poster="videos/images/eds7.png" src="videos/short/eds7.mp4" muted autoplay loop></video><label>PURPLE DENIM - Daytrippin</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/YfJ8EddylT5GPOKe8xi0hA/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="OnJuno Banking" data-videoSubName="Granny" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Agency + Production:</b> <a href='#'>@drinkadmilk</a><br> <b>Writer/Director:</b> <a href='#'>@Tristankimfilm</a><br> <b>Executive Producer:</b> <a href='#'>@alexmajher</a><br> <b>Creative Producer:</b> <a href='#'>@sleepyland0</a><br> <b>Producer:</b> <a href='#'>@bigballerkwall</a><br> <b>Editor:</b> <a href='#'>@devon.solwold</a><br> <b>Color:</b> <a href='#'>@vaflz @company_3</a><br> <b>Sound Designer:</b> <a href='#'>@sully_the_guy</a>"><video poster="videos/short/OnJunoBankingGranny.png" src="videos/short/OnJunoBankingGranny.mp4" muted autoplay loop></video><label>OnJuno Banking - Granny</label></div>
    <div class="seperator">Zack Pelletier</div> 
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/18ZVg50By1N1CR9pvnKjhQ/false/auto/auto/ffffff/000000/" data-title="Zack Pelletier" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="NFLPA" data-videoSubName="Rookie of the Year 2023" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Creative agency/ Production company:</b> <a href='#'>@omdigital</a><br> <b>Executive Producer:</b> <a href='#'>@dpcdtp</a><br> <b>Director:</b> <a href='#'>@pitch__please</a><br> <b>Producer:</b> <a href='#'>@sofiewar</a>"><video poster="videos/images/ezp1.png" src="videos/short/ezp1.mp4" muted autoplay loop></video><label>NFLPA - Rookie of the Year 2023</label></div>
    <div class="video zack-pelletier" data-longVideo="https://apollo.gosimian.com/share/v/CD-0Lxh9btZxIP7DcFPr-A/false/auto/auto/ffffff/000000/" data-title="Zack Pelletier" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="NHL" data-videoSubName="Hockey is Back" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@winterhalter_</a><br> <b>DP:</b> <a href='#'>@Cinesthetics</a><br> <b>Producer:</b> <a href='#'>@thejoelarkin</a><br> <b>Prod. Co:</b> <a href='#'>@Kursza</a><br> <b>Editor:</b> <a href='#'>@Zacksta Winterhalter_</a><br> <b>VFX:</b> <a href='#'>@filmwithryan</a><br> <b>Color:</b> <a href='#'>@RKMStudio_Color</a>"><video poster="videos/short/NHLHockeyisBack.png" src="videos/short/NHLHockeyisBack.mp4" muted autoplay loop></video><label>NHL - Hockey is Back</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/F-iBZ5QVpkJnpMEDcCBj0g/false/auto/auto/ffffff/000000/" data-title="Zack Pelletier" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="7uice" data-videoSubName="Vanson Leathers" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@a_ciggs & @medullamedia</a><br> <b>DP:</b> <a href='#'>@thommarch</a><br> <b>produced by:</b> <a href='#'>@parallelstudios</a><br> <b>Executive Producer:</b> <a href='#'>@simonchasalow @tonypillow</a><br> <b>Producer:</b> <a href='#'>@rossfriedman @ahilgey</a><br> <b>Editor:</b> <a href='#'>@zacksta</a>"><video poster="videos/images/ezp3.png" src="videos/short/ezp3.mp4" muted autoplay loop></video><label>7uice x Vanson Leathers </label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/3uSaBKukVQFuCKZxqVRCpA/false/auto/auto/ffffff/000000/" data-title="Zack Pelletier" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Chris Brown" data-videoSubName="Nightmares" data-credit="yes" data-credits="<h3>Apollo</h3> <b>DIRECTOR:</b> <a href='#'>@traviscolbert</a><br> <b>CREATIVE DIRECTOR:</b> <a href='#'>@chrisbrownofficial</a><br> <b>PRODUCER:</b> <a href='#'>PAUL FINAMORE</a><br> <b>PRODUCTION COMPANY:</b> <a href='#'>@projektstu</a><br> <b>DP:</b> <a href='#'>@henritaillon</a><br> <b>EDITORS:</b> <a href='#'>@_zacksta @henritaillon @traviscolbert</a><br> <b>COLORIST:</b> <a href='#'>@thomas.dauteuil</a>"><video poster="videos/images/ezp4.png" src="videos/short/ezp4.mp4" muted autoplay loop></video><label>Chris Brown - Nightmares</label></div>
    <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/s7w_utug7_nyaoW0tp05cw/false/auto/auto/ffffff/000000/" data-title="Zack Pelletier" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Louis the Child" data-videoSubName="How High" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@a_ciggs</a><br> <b>Executive Producer:</b> <a href='#'>@simonchasalow @tonypillow</a><br> <b>Production co:</b> <a href='#'>@parallelstudios</a><br> <b>DP:</b> <a href='#'>@owenschatz @a_ciggs</a><br> <b>Post House:</b> <a href='#'>@apolloposthouse</a><br> <b>Post Supervisor:</b> <a href='#'>@ap.mov</a>"><video poster="videos/images/ezp5.png" src="videos/short/ezp5.mp4" muted autoplay loop></video><label>Louis the Child - How High</label></div>
  </div> 
  
  <div class="editorsMain editorsLeftMain">
        <ul class="editorsLeft editors" style="padding-top: 8px;">
            <li class="active" data-start=0><a href="/roaster/editor">EDITOR</a></li>
            <li data-start=1><a href="/roaster/color">COLOR</a></li>
            <li data-start=2><a href="/roaster/sound">SOUND</a></li>
            <li data-start=3><a href="/roaster/vfx">VFX</a></li>
        </ul>
    </div>
    
    <div class="editorsMain editorsRightMain">
        <ul class="editorsRight editors EditorGroupUL">
            <li class="active" data-start=0><a href="/roaster/jamil-shaukat">Jamil Shaukat</a></li>  
            <li data-start=10><a href="/roaster/liam-tangum">Liam Tangum</a></li>
            <li data-start=18><a href="/roaster/griffin-olis">Griffin Olis</a></li>
            <li data-start=19><a href="/roaster/devon-solwold">Devon Solwold</a></li>
            <li data-start=20><a href="/roaster/zack-pelletier">Zack Pelletier</a></li>
            <!--<li data-start=21><a href="/roaster/jamil-shaukat">Jamil Shaukat</a></li>  
            <li data-start=22><a href="/roaster/liam-tangum">Liam Tangum</a></li>
            <li data-start=23><a href="/roaster/griffin-olis">Griffin Olis</a></li>
            <li data-start=24><a href="/roaster/devon-solwold">Devon Solwold</a></li>
            <li data-start=25><a href="/roaster/zack-pelletier">Zack Pelletier</a></li>
            <li><a style="color:transparent;">Inner</a></li>
            <li><a style="color:transparent;">Inner</a></li>
            <li><a style="color:transparent;">Inner</a></li>
            <li><a style="color:transparent;">Inner</a></li>--->
        </ul>
    </div>
    <div class="modal fade" id="videoModalPopup" tabindex="-1" role="dialog"> 
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="videoSupport">
                <div class="popupVideo" style="display:none;">
                    <iframe src="" frameborder="0" allow="autoplay" allowfullscreen=""></iframe>
                    <h3></h3>
                    <h4></h4>
                    <h5></h5>
                </div>
                <div class="creditPopupVideo" style="display:none;">
                    <div class="creditDetail">
                        <div class="leftSide">
                            <h3></h3>
                            <iframe src="" frameborder="0" allow="autoplay" allowfullscreen=""></iframe>
                        </div>
                        <div class="rightSide"></div>
                    </div>
                </div>
            </div>
            <ul class="screenshots">
                <li class="preview1">
                    <img src="https://appollo.360cloudcenter.com/griffin-olis/mlsepisode2/vlcsnap-2024-06-06-04h16m58s466.jpg">
                </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script> 
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script>
        $(document).on('click','div.video-container div.video',function(){
            var author = $(this).attr('data-author');
            var prev1 = $(this).attr('data-prev1');
            var prev2 = $(this).attr('data-prev2');
            var prev3 = $(this).attr('data-prev3');
            var prev4 = $(this).attr('data-prev4');
            var prev5 = $(this).attr('data-prev5');
            var prev6 = $(this).attr('data-prev6');
            var longVideo = $(this).attr('data-longVideo');
            var title = $(this).attr('data-videoName');
            var subtitle = $(this).attr('data-videoSubName');
            var credit = $(this).attr('data-credit');
            var credits = $(this).attr('data-credits');
            $('div#videoModalPopup ul.screenshots').html('');
            if(prev1!=''){
                $('div#videoModalPopup ul.screenshots').append('<li class="preview1"> <img src="'+prev1+'"> </li>');
            }
            if(prev2!=''){
                $('div#videoModalPopup ul.screenshots').append('<li class="preview2"> <img src="'+prev2+'"> </li>');
            }
            if(prev3!=''){
                $('div#videoModalPopup ul.screenshots').append('<li class="preview3"> <img src="'+prev3+'"> </li>');
            }
            if(prev4!=''){
                $('div#videoModalPopup ul.screenshots').append('<li class="preview4"> <img src="'+prev4+'"> </li>');
            }
            if(prev5!=''){
                $('div#videoModalPopup ul.screenshots').append('<li class="preview5"> <img src="'+prev5+'"> </li>');
            }
            if(prev6!=''){
                $('div#videoModalPopup ul.screenshots').append('<li class="preview6"> <img src="'+prev6+'"> </li>');
            }
            $('#videoModalPopup iframe').attr('src','');
            if(credit=='yes'){
                $('#videoModalPopup div.creditPopupVideo iframe').attr('src',longVideo);
                $('#videoModalPopup div.creditPopupVideo h3').text(title+' - '+subtitle);
                $('#videoModalPopup div.creditPopupVideo div.rightSide').html(credits);
                $('#videoModalPopup div.popupVideo').hide();
                $('#videoModalPopup div.creditPopupVideo').show();
            }else{
                $('#videoModalPopup div.popupVideo iframe').attr('src',longVideo);
                $('#videoModalPopup div.popupVideo h3').text(title);
                $('#videoModalPopup div.popupVideo h4').text(subtitle);
                $('#videoModalPopup div.popupVideo h5').text(author);
                $('#videoModalPopup div.creditPopupVideo').hide();
                $('#videoModalPopup div.popupVideo').show();
            }
            $('div#videoModalPopup').modal('show');
        });
        setTimeout(() => {
            $('div.editorsMain ul.editorsRight li').removeClass('active');
            $('div.editorsMain ul.editorsRight li[data-start="0"]').addClass('active');
            $('ul.editorsRight.editors.EditorGroupUL').animate({ scrollTop: 1 }, 0);
            $('div.insideHeader div.menuRight h4.authorsNames').text('Jamil Shaukat');
            $("html, body").animate({
                scrollTop: $(".video-container div.video.jamil-shaukat").offset().top-200
            }, 500);
        }, 100);
        window.addEventListener("scroll", handleScroll);
        function handleScroll() {
            const viewportHeight = window.innerHeight;
            const videos = document.querySelectorAll("div.video");
            videos.forEach(video => {
                const rect = video.getBoundingClientRect();
                const distanceFromCenter = Math.abs(rect.top + rect.height / 2 - viewportHeight / 2);
                const scale = Math.max(1.3 - distanceFromCenter / viewportHeight, 0.5);
                const opacity = Math.max(1.3 - distanceFromCenter / viewportHeight, 0.5);
                video.style.transform = `scale(${scale})`;
                video.style.opacity = opacity;
                if (scale > 1.2) {
                    const currentAuthor = video.getAttribute("data-author");
                    const currentTitle = video.getAttribute("data-title");
                    if (currentTitle === 'Jamil Shaukat') {
                        $('div.editorsMain ul.editorsRight li').removeClass('active');
                        $('div.editorsMain ul.editorsRight li').removeClass('scrollActive');
                        $('div.editorsMain ul.editorsRight li[data-start="0"]').addClass('active');
                        $('ul.editorsRight.editors.EditorGroupUL').animate({ scrollTop: 1 }, 0);
                        $('div.insideHeader div.menuRight h4.authorsNames').text('Jamil Shaukat');
                    }
                    if (currentTitle === 'Liam Tangum') {
                        $('div.editorsMain ul.editorsRight li').removeClass('active');
                        $('div.editorsMain ul.editorsRight li').removeClass('scrollActive');
                        $('div.editorsMain ul.editorsRight li[data-start="10"]').addClass('active');
                        $('ul.editorsRight.editors.EditorGroupUL').animate({ scrollTop: 47 }, 0);
                        $('div.insideHeader div.menuRight h4.authorsNames').text('Liam Tangum');
                    }
                    if (currentTitle === 'Griffin Olis') {
                        $('div.editorsMain ul.editorsRight li').removeClass('active');
                        $('div.editorsMain ul.editorsRight li').removeClass('scrollActive');
                        $('div.editorsMain ul.editorsRight li[data-start="18"]').addClass('active');
                        $('ul.editorsRight.editors.EditorGroupUL').animate({ scrollTop: 91 }, 0);
                        $('div.insideHeader div.menuRight h4.authorsNames').text('Griffin Olis');
                    }
                    if (currentTitle === 'Devon Solwold') {
                        $('div.editorsMain ul.editorsRight li').removeClass('active');
                        $('div.editorsMain ul.editorsRight li').removeClass('scrollActive');
                        $('div.editorsMain ul.editorsRight li[data-start="19"]').addClass('active');
                        $('ul.editorsRight.editors.EditorGroupUL').animate({ scrollTop: 135 }, 0);
                        $('div.insideHeader div.menuRight h4.authorsNames').text('Devon Solwold');
                    }
                    if (currentTitle === 'Zack Pelletier') {
                        $('div.editorsMain ul.editorsRight li').removeClass('active');
                        $('div.editorsMain ul.editorsRight li').removeClass('scrollActive');
                        $('div.editorsMain ul.editorsRight li[data-start="20"]').addClass('active'); 
                        $('ul.editorsRight.editors.EditorGroupUL').animate({ scrollTop: 180 }, 0);
                        $('div.insideHeader div.menuRight h4.authorsNames').text('Zack Pelletier');
                    }
                }
            });
        }
    // });
    document.addEventListener("DOMContentLoaded", function(event){
        var videoContainer = document.querySelector('.video-container'); 
        var videoHTML = `    
            <div class="seperator">Jamil Shaukat</div>     
            
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/7w52-uK-KwO2eWCfwCEDjQ/false/auto/auto/ffffff/000000" data-title="Ruroc - Berserker" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Ruroc - Berserker" data-videoSubName="Anytime, Anywhere" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>KC Locke</a><br> <b>Executive Producer:</b> <a href='#'>KC Locke</a><br> <b>Producer:</b> <a href='#'>Lewis Nicholson</a><br> <b>Production Company:</b> <a href='#'>Swords & Eagles</a><video poster="videos/images/nv1.jpg" src="videos/short/nv1.mp4" muted autoplay loop></video><label>Ruroc - Berserker</label></div>
            
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/-q-nJk-MzyUmkAPIljAdAw/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Look" data-videoSubName="Fantastic" data-credit="no" data-credits=""><video poster="videos/images/nv2.jpg" src="videos/short/nv2.mp4" muted autoplay loop></video><label>Look Fantastic</label></div>
           
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/Z_N4ZKx8zseoxuWWEO5J9A/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Drama Call" data-videoSubName="Heaviest in the Game" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@Rawtape</a><br> <b>Production Company:</b> <a href='#'>@Antfarmfilmservices</a><br> <b>DP: <a href='#'>@jameskilleendop</a><br> <b>Post Production:</b> <a href='#'>@absolute_post</a><br> <b>Colour Producer:</b> <a href='#'>@ollieireland</a><br> <b>Colourist:</b> <a href='#'>@turners_colour</a><br> <b>Sound Producer:</b> <a href='#'>@Maddylebel</a><br> <b>Sound Design:</b> <a href='#'>@Argington</a>"><video poster="videos/images/nv3.jpg" src="videos/short/nv3.mp4" muted autoplay loop></video><label>Drama Call - Heaviest in the Game</label></div>
            
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/OoYHiz7arVaXh-_3xR3o7g/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="CP Company" data-videoSubName="Manchester City" data-credit="yes" data-credits=""><video poster="videos/images/nv4.jpg" src="videos/short/nv4.mp4" muted autoplay loop></video><label>CP Company x Manchester City</label></div>
            
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/4QqEVVuhldXN_i8Bnr1ZYw/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Boohoo Man" data-videoSubName="World Cup" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> KC Locke<br> <b>Producer:</b> Lewis Nicholson<br> <b>Production Company:</b> Swords & Eagles<br> <b>Exec Producer/ Directors Rep:</b> Marisa Garner<br> <b>DOP:</b> Rowan Biddiscombe<br> <b>Production Manager & Art Director:</b> Jenny O’Sullivan<br> <b>Editor:</b> Jamil Shaukat"><video poster="videos/images/nv5.jpg" src="videos/short/nv5.mp4" muted autoplay loop></video><label>Boohoo Man - World Cup</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/rfxS53q1G8VO6asIkOW-mg/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Meekz" data-videoSubName="Mini Me's" data-credit="no" data-credits=""><video poster="videos/images/nv6.jpg" src="videos/short/nv6.mp4" muted autoplay loop></video><label>Meekz - Mini Me's </label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/7FWkr5CFwzqaqdHiwrvlww/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Ed Sheeran" data-videoSubName="Take Me Back To London feat. Stormzy, Jaykae & Aitch" data-credit="no" data-credits=""><video poster="videos/images/nv7.jpg" src="videos/short/nv7.mp4" muted autoplay loop></video><label>Ed Sheeran - Take Me Back To London feat. Stormzy, Jaykae & Aitch</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/qhF_Zr-_wpZEXebRRPM4YA/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Aitch" data-videoSubName="Learning Curve"  data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> KC LOCKE<br> <b>Production Company:</b> Swords & Eagles<br> <b>Exec Producer/Directors:</b> Rep Marisa Garner<br> <b>DOP:</b> Pieter Synman<br> <b>Production Designer:</b> Jenny O’ Sullivan<br> <b>Editor:</b> Jamil Shaukat<br> <b>Production Manager:</b> Ella Taylor-Palfrey"><video poster="videos/images/nv8.jpg" src="videos/short/nv8.mp4" muted autoplay loop></video><label>Aitch - Learning Curve</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/L3HZIYNTMRPdQazo9r5jIQ/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="M Huncho & Headie One" data-videoSubName="Warzone" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> KC Locke<br> <b>Producer:</b> Lewis Nicholson<br> <b>Production Company:</b> Swords & Eagles ⚔️🦅<br> <b>Exec Producer:</b> Marisa Garner<br> <b>DOP:</b> Matthew Emvin Taylor<br> <b>Art Director:</b> Jenny O’Sullivan<br> <b>Editor:</b> Jamil Shaukat<br> <b>Production Manager:</b> Ella Taylor-Palfrey"><video poster="videos/images/nv9.jpg" src="videos/short/nv9.mp4" muted autoplay loop></video><label>M Huncho & Headie One - Warzone</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/e_xK1H4Fp-Y8rhQhkSCckA/false/auto/auto/ffffff/000000/" data-title="Jamil Shaukat" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="David Guetta" data-videoSubName="BEBE" data-credit="no" data-credits=""><video poster="videos/images/nv10.jpg" src="videos/short/nv10.mp4" muted autoplay loop></video><label>David Guetta x BEBE</label></div>
            <div class="seperator">Liam Tangum</div>    
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/l4iJTcmvUc9kqSQ3mcktIA/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Oakely" data-videoSubName="Kylian Mbappe" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Creative and production:</b> <a href='#'>@steptstudios</a><br> <b>Producer:</b> <a href='#'>@alexa_hinson</a><br> <b>Head of creative:</b> <a href='#'>@rachcity</a><br> <b>Production manager:</b> <a href='#'>@ioladgsn</a><br> <b>Director:</b> <a href='#'>@joaquimbayle</a><br> <b>Assistant Director:</b> <a href='#'>@basile_boudoux</a><br> <b>DP:</b> <a href='#'>@marquesangelo</a>"><video poster="videos/images/nv11.jpg" src="videos/short/nv11.mp4" muted autoplay loop></video><label>Oakely - Kylian Mbappe</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/dV859sXWTPiERH5CF6iyTQ/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="YMI Jeans" data-videoSubName="RFM" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> SOFIA CRISTINA ALVAREZ<br> <b>Producer:</b> MARLYN RODRIGUEZ<br> <b>Creative Director:</b> DALIA GISELE SAFFAR<br> <b>Editor:</b> LIAM TANGUM<br> <b>Colorist:</b> DYLAN HAGEMAN<br> <b>Sound Designer:</b> GLENN MORISSE"><video poster="videos/images/nv12.jpg" src="videos/short/nv12.mp4" muted autoplay loop></video><label>RFM Jeans</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/2RyALL3vM1bbYlXn6hEOjQ/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Brooks" data-videoSubName="Sounds of Trail Running" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Production:</b> <a href='#'>@steptstudios</a><br> <b>Post Production:</b> <a href='#'>@lockteditorial</a><br> <b>Director:</b> <a href='#'>Liam Tangum</a><br> <b>DP:</b> <a href='#'>@nash.howe</a><br> <b>Head of Post:</b> <a href='#'>@mr.deliverables</a>"><video poster="videos/images/nv13.jpg" src="videos/short/nv13.mp4" muted autoplay loop></video><label>Brooks - Sounds of Trail Running</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/0oRqHg7RMp9cRtecFGac4g/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Bevel" data-videoSubName="Kyle Pitts" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director / DP:</b> <a href='#'>@franklinspov</a> <h3>Produced by The Kitchen Table</h3> <b>Post Production Company:</b> <a href='#'>@apolloposthouse</a><br> <b>Head of Post:</b> <a href='#'>@ap.mov</a><br> <b>Post Supervisor:</b> <a href='#'>@nasserboulaich</a><br> <b>Editor:</b> <a href='#'>@ltangum</a><br> <b>Colorist:</b> <a href='#'>@brianchrls</a>"><video poster="videos/images/nv14.jpg" src="videos/short/nv14.mp4" muted autoplay loop></video><label>Bevel - Kyle Pitts</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/QnNDO5jJPiweNaYkDbVNkQ/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Nowness" data-videoSubName="Short Film" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> Leo Pfeifer<br> <b>Prouction:</b> Alto Visuals<br> <b>Editor:</b> Liam Tangum<br> <b>Sound Design:</b> Chris Fleming<br> <b>Production Director:</b> Ariana Massery"><video poster="videos/images/nv15.jpg" src="videos/short/nv15.mp4" muted autoplay loop></video><label>Nowness - Short Film</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/CmHy4CgsSoqo5K58skbxDw/false/auto/auto/ffffff/000000/" data-title="Liam Tangum" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="A Slice of Paradise" data-videoSubName="Short Film" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> Liam Tangum<br> <b>Executive Producers:</b> No Laying Up<br> <b>Cinematographer:</b> Jake Coury<br> <b>Producer:</b> Michael Nicholas<br> <b>Editors:</b> Liam Tangum & Lindsay Wilkins"><video poster="videos/images/nv16.jpg" src="videos/short/nv16.mp4" muted autoplay loop></video><label>A Slice of Paradise - Short Film</label></div>
            <div class="seperator">Griffin Olis</div> 
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/1z2wxMuQOojv0_l3j_3BUA/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Adidas" data-videoSubName="Speed Juice" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@dannymcnabb_</a><br> <b>Production Company:</b> <a href='#'>@resinprojects</a><br> <b>Motion Producer:</b> <a href='#'>@anno & @sydnyfuruichi</a><br> <b>First AD:</b> <a href='#'>@justbearit</a><br> <b>DP:</b> <a href='#'>@cory.burmester</a>"><video poster="videos/images/nv17.jpg" src="videos/short/nv17.mp4" muted autoplay loop></video><label>Adidas - Speed Juice</label></div> 
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/hpcySoCWdlWWHzaW6P5WWA/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Fear of God" data-videoSubName="" data-credit="no" data-credits=""><video poster="videos/images/nv18.jpg" src="videos/short/nv18.mp4" muted autoplay loop></video><label>Fear of God </label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/n0LFcwPS9X72xQRkpvugzw/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Kai Cenat" data-videoSubName="Going Professional" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Production Company:</b> <a href='#'>@blackscreenproductionsinc</a><br> <b>Director:</b> <a href='#'>@directorprime @lach531</a><br> <b>Executive Producers:</b> <a href='#'>@moniquescarrillo @directorprime</a><br> <b>Producer:</b> <a href='#'>@henryjwolf</a><br> <b>DP:</b> <a href='#'>@jon.charles</a>"><video poster="videos/images/nv19.jpg" src="videos/short/nv19.mp4" muted autoplay loop></video><label>Kai Cenat - Going Professional</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/eHWf8zsSuiwys697NlDV3A/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Under Armour" data-videoSubName="Men Unstoppable Collection" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@waboosh</a><br> <b>Executive Producers/Parallel Studios:</b> <a href='#'>@tonypillow @Simonchasalow</a><br> <b>Executive Producer/GoBam:</b> <a href='#'>Chris Charlton</a><br> <b>Lead Producer:</b> <a href='#'>@msjonesa</a><br> <b>Head of Post:</b> <a href='#'>@ap.mov</a><br> <b>DP:</b> <a href='#'>@cory.burmester</a>"><video poster="videos/images/nv20.jpg" src="videos/short/nv20.mp4" muted autoplay loop></video><label>Under Armour - Men's Unstoppable Collection </label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/k84zVfx6eUANCz9rc-axFQ/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Kai Cenat x iShowSpeed Streamshow" data-videoSubName="Kai Cenat" data-credit="no" data-credits=""><video poster="videos/images/nv21.jpg" src="videos/short/nv21.mp4" muted autoplay loop></video><label>Kai Cenat x iShowSpeed</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/5jtkQ-J-7bk3e1C4p_1hwQ/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="MLS & Apple TV" data-videoSubName="Beyond the Pitch - Episode 2" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Editor:</b> <a href='#'>@blaizefobbe</a><br> <b>Post Production Supervisor:</b> <a href='#'>@ap.mov</a><br> <b>Director:</b> <a href='#'>@mediadon</a><br> <b>Executive Producers:</b> <a href='#'>@ap.mov @justnateloucks</a><br> <b>Producers:</b> <a href='#'>@waboosh @masendaforever</a><br> <b>Production Manager:</b> <a href='#'>@connectwithdiego</a><br> <b>Media Company:</b> <a href='#'>@boardroom</a><br> <b>Production Co:</b> <a href='#'>@parallelstudios</a>"><video poster="videos/images/MLS_Episode_2.png" src="videos/short/MLS_Episode_2.mp4" muted autoplay loop></video><label>MLS & Apple TV - Beyond the Pitch - Episode 2</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/_m2_Z8QG2n7FMj9u6qLWZA/false/auto/auto/ffffff/000000/" data-title="Griffin Olis" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="MLS & Apple TV" data-videoSubName="Beyond the Pitch - Episode 4" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Editor:</b> <a href=''>@blaizefobbe</a><br> <b>Post Production Supervisor:</b> <a href=''>@ap.mov</a><br> <b>Director:</b> <a href=''>@mediadon</a><br> <b>Executive Producers:</b> <a href=''>@ap.mov @justnateloucks</a><br> <b>Producers:</b> <a href=''>@waboosh @masendaforever</a><br> <b>Production Manager:</b> <a href=''>@connectwithdiego</a><br> <b>Media Company:</b> <a href=''>@boardroom</a><br> <b>Production Co:</b> <a href=''>@parallelstudios</a>"><video poster="videos/images/MLS_Episode_4.png" src="videos/short/MLS_Episode_4.mp4" muted autoplay loop></video><label>MLS & Apple TV - Beyond the Pitch- Episode 4</label></div>
            <div class="seperator">Devon Solwold</div> 
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/hKEJPCvrM6F1f_D8m775gw/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Bodega" data-videoSubName="New Balance" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@nottonightmike</a><br> <b>Producer:</b> <a href='#'>@lizkraushaar</a><br> <b>DOP:</b> <a href='#'>@kajdickson</a><br> <b>Editor + Sound Designer:</b> <a href='#'>@devon.solwold</a><br> <b>Music:</b> <a href='#'>@mr.audreyhorne</a><br> <b>Executive Producer:</b> <a href='#'>@alexmajher</a>"><video poster="videos/images/eds1.png" src="videos/short/eds1.mp4" muted autoplay loop></video><label>Bodega x New Balance</label></div> 
            
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/tP8hab455lYbINecxlO4UA/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Bodega x G Shock" data-videoSubName="Anytime, Anywhere" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>Michael B Janey @nottonightmike</a><br> <b>Cinematographer:</b> <a href='#'>Kai Dickson @kaj_dickson</a><br> <b>Post Producer:</b> <a href='#'>Elizabeth Kraushaar @liz_kraushaar</a><br> <b>Editor + Sound Designer:</b> <a href='#'>Devon Solwold @devon.solwold</a><br> <b>Colorist:</b> Kai Dickson<br> <b>Agency:</b> <a href='#'>@drinkadmilk</a>"><video poster="videos/short/bodega-g-shock-anytime-anywhere.png" src="videos/short/bodega-g-shock-anytime-anywhere.mp4" muted autoplay loop></video><label>Bodega x G Shock - Anytime, Anywhere</label></div>
            
            
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/7w52-uK-KwO2eWCfwCEDjQ/false/auto/auto/ffffff/000000" data-title="Ruroc - Berserker" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Ruroc - Berserker" data-videoSubName="Anytime, Anywhere" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>KC Locke</a><br> <b>Executive Producer:</b> <a href='#'>KC Locke</a><br> <b>Producer:</b> <a href='#'>Lewis Nicholson</a><br> <b>Production Company:</b> <a href='#'>Swords & Eagles</a><video poster="videos/images/nv1.jpg" src="videos/short/nv1.mp4" muted autoplay loop></video><label>Ruroc - Berserker</label></div>
            
            
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/Kj037VYYf3TRWAyj2X9grw/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="OKEM" data-videoSubName="Short Film" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> Joshua Okwuosa<br> <b>Cinematography:</b> Kai Dickson<br> <b>Music:</b> Jake Hull<br> <b>Editing:</b> Devon Solwold<br> <b>Producer:</b> Liz Kraushaar"><video poster="videos/images/eds3.png" src="videos/short/eds3.mp4" muted autoplay loop></video><label>OKEM - Short Film</label></div>
            
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/MdBuv2VRG7aBrCpyi2NlzQ/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Eem Triplin" data-videoSubName="What Da Opp Said" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@waboosh</a><br> <b>Executive Producers:</b> <a href='#'>@tonypillow @simonchasalow @_lucasprevost</a><br> <b>Producer:</b> <a href='#'>@noursayeh</a><br> <b>Production Manager:</b> <a href='#'>@natallejastrow</a><br> <b>Head of Production Support:</b> <a href='#'>@tj.gormley</a><br> <b>Production Company:</b> <a href='#'>@parallelstudios</a>"><video poster="videos/images/eds4.png" src="videos/short/eds4.mp4" muted autoplay loop></video><label>Eem Triplin - What Da Opp Said</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/roJJm677DwOEfWAHUBszjw/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="$NOT feat. Zilla Kami" data-videoSubName="0 PERCENT" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@jmp</a><br> <b>Executive Producer:</b> <a href='#'>@joeyszela</a><br> <b>Producer:</b> <a href='#'>@tru.drew</a><br> <b>DP:</b> <a href='#'>@joelwolt</a><br> <b>Production Company:</b> <a href='#'>@paperwork</a>"><video poster="videos/short/NOT-Ft-Zilla-Kami-0-PERCENT.png" src="videos/short/NOT-Ft-Zilla-Kami-0-PERCENT.mp4" muted autoplay loop></video><label>$NOT feat. Zilla Kami - 0 PERCENT</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/OajoX7MS0eM11zx97Mov9Q/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Run that Shit!" data-videoSubName="Short Film" data-credit="yes" data-credits="<h3>Apollo</h3> <b>EXECUTIVE PRODUCERS:</b> Tristan Kim, Harrison Kracht<br> <b>DIRECTOR:</b> Tristan Kim<br> <b>WRITTEN BY:</b> Tristan Kim, Will Allyn Robinson<br> <b>DIRECTOR OF PHOTOGRAPHY:</b> Harrison Kracht"><video poster="videos/images/eds6.png" src="videos/short/eds6.mp4" muted autoplay loop></video><label>Run that Shit! Short Film</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/pnUrDJ8rUy0z_wgrQsLUPg/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="PURPLE DENIM" data-videoSubName="Daytrippin" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Edit, Sound, VFX:</b> <a href='#'>@devon.solwold</a><br> <b>Studio:</b> <a href='#'>@drinkadmilk</a><br> <b>Producer:</b> <a href='#'>@alexmajher</a>"><video poster="videos/images/eds7.png" src="videos/short/eds7.mp4" muted autoplay loop></video><label>PURPLE DENIM - Daytrippin</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/YfJ8EddylT5GPOKe8xi0hA/false/auto/auto/ffffff/000000/" data-title="Devon Solwold" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="OnJuno Banking" data-videoSubName="Granny" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Agency + Production:</b> <a href='#'>@drinkadmilk</a><br> <b>Writer/Director:</b> <a href='#'>@Tristankimfilm</a><br> <b>Executive Producer:</b> <a href='#'>@alexmajher</a><br> <b>Creative Producer:</b> <a href='#'>@sleepyland0</a><br> <b>Producer:</b> <a href='#'>@bigballerkwall</a><br> <b>Editor:</b> <a href='#'>@devon.solwold</a><br> <b>Color:</b> <a href='#'>@vaflz @company_3</a><br> <b>Sound Designer:</b> <a href='#'>@sully_the_guy</a>"><video poster="videos/short/OnJunoBankingGranny.png" src="videos/short/OnJunoBankingGranny.mp4" muted autoplay loop></video><label>OnJuno Banking - Granny</label></div>
            <div class="seperator">Zack Pelletier</div> 
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/18ZVg50By1N1CR9pvnKjhQ/false/auto/auto/ffffff/000000/" data-title="Zack Pelletier" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="NFLPA" data-videoSubName="Rookie of the Year 2023" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Creative agency/ Production company:</b> <a href='#'>@omdigital</a><br> <b>Executive Producer:</b> <a href='#'>@dpcdtp</a><br> <b>Director:</b> <a href='#'>@pitch__please</a><br> <b>Producer:</b> <a href='#'>@sofiewar</a>"><video poster="videos/images/ezp1.png" src="videos/short/ezp1.mp4" muted autoplay loop></video><label>NFLPA - Rookie of the Year 2023</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/CD-0Lxh9btZxIP7DcFPr-A/false/auto/auto/ffffff/000000/" data-title="Zack Pelletier" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="NHL" data-videoSubName="Hockey is Back" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@winterhalter_</a><br> <b>DP:</b> <a href='#'>@Cinesthetics</a><br> <b>Producer:</b> <a href='#'>@thejoelarkin</a><br> <b>Prod. Co:</b> <a href='#'>@Kursza</a><br> <b>Editor:</b> <a href='#'>@Zacksta Winterhalter_</a><br> <b>VFX:</b> <a href='#'>@filmwithryan</a><br> <b>Color:</b> <a href='#'>@RKMStudio_Color</a>"><video poster="videos/short/NHLHockeyisBack.png" src="videos/short/NHLHockeyisBack.mp4" muted autoplay loop></video><label>NHL - Hockey is Back</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/F-iBZ5QVpkJnpMEDcCBj0g/false/auto/auto/ffffff/000000/" data-title="Zack Pelletier" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="7uice" data-videoSubName="Vanson Leathers" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@a_ciggs & @medullamedia</a><br> <b>DP:</b> <a href='#'>@thommarch</a><br> <b>produced by:</b> <a href='#'>@parallelstudios</a><br> <b>Executive Producer:</b> <a href='#'>@simonchasalow @tonypillow</a><br> <b>Producer:</b> <a href='#'>@rossfriedman @ahilgey</a><br> <b>Editor:</b> <a href='#'>@zacksta</a>"><video poster="videos/images/ezp3.png" src="videos/short/ezp3.mp4" muted autoplay loop></video><label>7uice x Vanson Leathers </label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/3uSaBKukVQFuCKZxqVRCpA/false/auto/auto/ffffff/000000/" data-title="Zack Pelletier" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Chris Brown" data-videoSubName="Nightmares" data-credit="yes" data-credits="<h3>Apollo</h3> <b>DIRECTOR:</b> <a href='#'>@traviscolbert</a><br> <b>CREATIVE DIRECTOR:</b> <a href='#'>@chrisbrownofficial</a><br> <b>PRODUCER:</b> <a href='#'>PAUL FINAMORE</a><br> <b>PRODUCTION COMPANY:</b> <a href='#'>@projektstu</a><br> <b>DP:</b> <a href='#'>@henritaillon</a><br> <b>EDITORS:</b> <a href='#'>@_zacksta @henritaillon @traviscolbert</a><br> <b>COLORIST:</b> <a href='#'>@thomas.dauteuil</a>"><video poster="videos/images/ezp4.png" src="videos/short/ezp4.mp4" muted autoplay loop></video><label>Chris Brown - Nightmares</label></div>
            <div class="video" data-longVideo="https://apollo.gosimian.com/share/v/s7w_utug7_nyaoW0tp05cw/false/auto/auto/ffffff/000000/" data-title="Zack Pelletier" data-author="EDIT" data-prev1="" data-prev2="" data-prev3="" data-prev4="" data-prev5="" data-prev6="" data-videoName="Louis the Child" data-videoSubName="How High" data-credit="yes" data-credits="<h3>Apollo</h3> <b>Director:</b> <a href='#'>@a_ciggs</a><br> <b>Executive Producer:</b> <a href='#'>@simonchasalow @tonypillow</a><br> <b>Production co:</b> <a href='#'>@parallelstudios</a><br> <b>DP:</b> <a href='#'>@owenschatz @a_ciggs</a><br> <b>Post House:</b> <a href='#'>@apolloposthouse</a><br> <b>Post Supervisor:</b> <a href='#'>@ap.mov</a>"><video poster="videos/images/ezp5.png" src="videos/short/ezp5.mp4" muted autoplay loop></video><label>Louis the Child - How High</label></div>
        `;
        videoContainer.insertAdjacentHTML('afterbegin', videoHTML);
        window.addEventListener('scroll', () => {
            var scrollable = document.documentElement.scrollHeight - window.innerHeight;
            var scrolled = window.scrollY;
            if (Math.ceil(scrolled) >= scrollable) {
                videoContainer.insertAdjacentHTML('beforeend', videoHTML);
            }
            if (scrolled === 0) {
                videoContainer.insertAdjacentHTML("afterbegin", videoHTML);
                window.scrollTo(0, videoContainer.offsetHeight);
            }
        });
    });
    
  
  </script>
</body>
</html>